language: ruby
cache: bundler
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  #- 2.4 
  #- ruby-head
gemfile:
  - gemfiles/ruby-2.1.gemfile
  - gemfiles/ruby-current.gemfile
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/ruby-current.gemfile
before_install: npm install --global uglify-js && which uglify-js
script: bundle exec rake test