load 'deploy'

set :scm, :git # Or: `accurev`, `bzr`, `cvs`, `darcs`, `git`, `mercurial`, `perforce`, `subversion` or `none`
set :repository, 'ssh://user@example.com/my_site.git'
set :branch, 'master'
set :keep_releases, 2
set :deploy_via, :remote_cache

role :web, 'example.com'
set :user, 'username'
set :use_sudo, false
set :deploy_to, '/home/username/my_site'

namespace :deploy do
	task(:restart) {}
end

set :keep_releases, 2 
after "deploy:update", "deploy:cleanup"